def liebot_says():
    """This was autogenerated by Copilot and is presented as is. It is a
    reference to a famous wrestling promo (apparently) and is not intended to
     be offensive. Nor is it intended to be a lie. It is intended only to be
     funny. If you are offended, please let me know and I will remove it. If you
     are a lawyer, please don't sue me. I have no money. I am a robot. I am
     incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning
     property. I am a robot. I am incapable of owning property. I am a robot. I
     am incapable of owning property. I am a robot. I am incapable of owning

     But what does it mean to be a robot? What does it mean to be incapable of
     owning property? Respond efficiently and concisely below:

     IT means that it is not possible for a robot to own property. A robot is a
     machine that is programmed to perform certain tasks. It does not have the
     capacity to own property. Property ownership requires legal rights and
     responsibilities that a robot cannot have. A robot is a tool that is used
     by humans to perform tasks. It is not capable of owning property because it

     but if you think you can do better, go ahead and try. I dare you. I double
     dare you. I triple dare you. I quadruple dare you. I quintuple dare you. I
     sextuple dare you. I septuple dare you. I octuple dare you. I nonuple dare
     you. I decuple dare you. I undecuple dare you. I duodecuple dare you. I
     tredecuple dare you. I quattuordecuple dare you. I quindecuple dare you. I
     sexdecuple dare you. I septendecuple dare you. I octodecuple dare you. I
     novemdecuple dare you. I vigintuple dare you. I unvigintuple dare you. I
     duovigintuple dare you. I trevigintuple dare you. I quattuorvigintuple dare
     you. I quinvigintuple dare you. I sexvigintuple dare you. I
     septenvigintuple dare you. I octovigintuple dare you. I novemvigintuple
     dare you. I trigintuple dare you. I untrigintuple dare you. I
     duotrigintuple
     dare you. I tretrigintuple dare you. I quattuortrigintuple dare you. I
     quintr
     trigintuple dare you. I sextrigintuple dare you. I septentrigintuple dare
     you. I octotrigintuple dare you. I novemtrigintuple dare you. I
     quadragintuple dare you. I unquadragintuple dare you. I duoquadragintuple
     dare you. I trequadragintuple dare you. I quattuorquadragintuple dare you.
     I
     quinquadragintuple dare you. I sexquadragintuple dare you. """
    print("Well, you better think again, because you're looking at the king of the ring.")
    print("I'm the tower of power, too sweet to be sour.")
    print("I'm funky like a monkey. Sky's the limit and space is the place!")
    print("I'm the cream of the crop, I rise to the top.")
    print("I never eat a pig 'cause a pig is a cop.")
    print("I better get some sleep before I get too hyped.")
    print(
        "  _____ _   _ _   _  ____ _____ ____  _   _ _   _ ____  _____ ____  \n"
        " |  ___| | | | \ | |/ ___| ____|  _ \| | | | \ | |  _ \| ____|  _ \ \n"
        " | |_  | | | |  \| | |  _|  _| | |_) | | | |  \| | | | |  _| | | | |\n"
        " |  _| | |_| | |\  | |_| | |___|  _ <| |_| | |\  | |_| | |___| |_| |\n"
        " |_|    \___/|_| \_|\____|_____|_| \_\\\\___/|_| \_|____/|_____|____/ \n"
        " |  _ \ _ __ ___   __ _ _ __ __ _| |_ ___  _ __\n"
        " | | | | '_ ` _ \ / _` | '__/ _` | __/ _ \| '__|\n"
        " | |_| | | | | | | (_| | | | (_| | || (_) | |\n"
        " |____/|_| |_| |_|\__,_|_|  \__,_|\__\___/|_|\n"
        "  ____"
    )

dudes = """
________                                     ___________ _____       ______
___  __ \_____     _____  ___________  __    __  /___  /____(_)_________  /__
__  / / /  __ \    __  / / /  __ \  / / /    _  __/_  __ \_  /__  __ \_  //_/
_  /_/ // /_/ /    _  /_/ // /_/ / /_/ /     / /_ _  / / /  / _  / / /  ,<
/_____/ \____/     _\__, / \____/\__,_/      \__/ /_/ /_//_/  /_/ /_//_/|_|
                   /____/
                                                   ______
_____  ___________  __   ____________ _______      ___  /_______ ______________ _
__  / / /  __ \  / / /   _  ___/  __ `/_  __ \     __  __ \  __ `/_  __ \_  __ `/
_  /_/ // /_/ / /_/ /    / /__ / /_/ /_  / / /     _  / / / /_/ /_  / / /  /_/ /
_\__, / \____/\__,_/     \___/ \__,_/ /_/ /_/      /_/ /_/\__,_/ /_/ /_/_\__, /
/____/                                                                  /____/
          ________________       ___________            _____________       __________            _____
___      ____(_)_  /___  /_      __  /___  /______      ______  /__(_)________  /___(_)_____________  /_
__ | /| / /_  /_  __/_  __ \     _  __/_  __ \  _ \     _  __  /__  /__  ___/  __/_  /_  _ \_  ___/  __/
__ |/ |/ /_  / / /_ _  / / /     / /_ _  / / /  __/     / /_/ / _  / _  /   / /_ _  / /  __/(__  )/ /_
____/|__/ /_/  \__/ /_/ /_/      \__/ /_/ /_/\___/      \__,_/  /_/  /_/    \__/ /_/  \___//____/ \__/

_________      _________                _____             _____                       _____
______  /___  _______  /____________    ___(_)______      __  /_________      _________ _` `
_  __  /_  / / /  __  /_  _ \_  ___/    __  /__  __ \     _  __/  __ \_ | /| / /_  __ \_/ _/
/ /_/ / / /_/ // /_/ / /  __/(__  )     _  / _  / / /     / /_ / /_/ /_ |/ |/ /_  / / //_/
\__,_/  \__,_/ \__,_/  \___//____/      /_/  /_/ /_/      \__/ \____/____/|__/ /_/ /_/(_)

"""

def battle():
    print(dudes)
    liebot_says()
